[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed = 460800
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=1
build_src_filter = +<*> -<test_main.cpp>
lib_deps =
    bblanchon/ArduinoJson@^7.1.0
    adafruit/Adafruit NeoPixel@^1.12.3

; ===== 硬件自检环境 =====
; 烧录: pio run -e test -t upload
[env:test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed = 460800
build_src_filter = -<*> +<test_main.cpp>
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=1
lib_deps =
